version: '2'

services:
  ci-build:
    image: mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019/ltsc2016
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./MHC_ASPNetCore.sln && dotnet publish ./MHC_ASPNetCore.sln -c Release -o ./obj/Docker/publish"
