version: '2'

services:
  ci-build:
    image: microsoft/aspnetcore:2.0.3
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./MHC_ASPNetCore.sln && dotnet publish ./MHC_ASPNetCore.sln -c Release -o ./obj/Docker/publish"
